public enum MessageType {

    GET_AUTHORIZATION,
    AUTHORIZATION_SUCCESSFUL,
    AUTHORIZATION_FAIL,
    COMMAND_NOT_RECOGNIZED,
    FILE_LIST,
    GET_FILE_LIST,
    FILE,
    DELETE_FILE,
    DIR,
    GET
}
